name: buf

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}
      
      - name: Lint
        run: buf lint
      
      - name: Format check
        run: buf format --diff --exit-code
      
      - name: Breaking change detection
        if: github.event_name == 'pull_request'
        run: buf breaking --against "https://github.com/${{ github.repository }}.git#branch=main"

  generate:
    runs-on: ubuntu-latest
    needs: lint-and-format
    steps:
      - uses: actions/checkout@v4
      
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}
      
      - name: Generate code
        run: buf generate
      
      - name: Upload generated Go code
        uses: actions/upload-artifact@v4
        with:
          name: generated-go
          path: gen/go/
      
      - name: Upload generated TypeScript code
        uses: actions/upload-artifact@v4
        with:
          name: generated-ts
          path: gen/ts/

  publish:
    runs-on: ubuntu-latest
    needs: [lint-and-format, generate]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}
      
      - name: Push to BSR
        run: buf push
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}