name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: write
  packages: write

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}
      
      - name: Lint
        run: buf lint
      
      - name: Format check
        run: buf format --diff --exit-code
      
      - name: Breaking change detection
        if: github.event_name == 'pull_request'
        continue-on-error: true
        run: buf breaking --against "https://github.com/${{ github.repository }}.git#branch=main"

  generate-and-test:
    runs-on: ubuntu-latest
    needs: lint-and-format
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}
      
      - name: Install mockgen
        run: go install github.com/golang/mock/mockgen@latest
      
      - name: Generate code
        run: buf generate
      
      - name: Generate mocks
        run: |
          # Generate mocks for gRPC services
          mkdir -p gen/go/clients/dnd5e/api/v1alpha1/mocks
          mockgen -source=gen/go/clients/dnd5e/api/v1alpha1/character_grpc.pb.go -destination=gen/go/clients/dnd5e/api/v1alpha1/mocks/character_service.go -package=mocks
      
      - name: Test Go compilation
        run: |
          cd gen/go
          go mod init clients
          # Add replace directive to use local generated code
          echo "replace clients => ./" >> go.mod
          go mod tidy
          go build ./...
      
      - name: Install TypeScript dependencies
        run: npm ci
      
      - name: Test TypeScript compilation
        run: |
          npx tsc --noEmit --project tsconfig.json
      
      - name: Upload generated artifacts
        uses: actions/upload-artifact@v4
        with:
          name: generated-code
          path: gen/

  publish-packages:
    runs-on: ubuntu-latest
    needs: [lint-and-format, generate-and-test]
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
      
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}
      
      - name: Install mockgen
        run: go install github.com/golang/mock/mockgen@latest
      
      - name: Generate all code
        run: |
          buf generate
          mkdir -p gen/go/clients/dnd5e/api/v1alpha1/mocks
          mockgen -source=gen/go/clients/dnd5e/api/v1alpha1/character_grpc.pb.go -destination=gen/go/clients/dnd5e/api/v1alpha1/mocks/character_service.go -package=mocks
      
      - name: Setup Go module
        run: |
          cd gen/go
          go mod init clients
          go mod tidy
      
      - name: Create release branch
        run: |
          # Create or update release branch with generated code
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Create release branch
          git checkout -B latest
          
          # Remove gen/ from gitignore temporarily
          sed '/^gen\/$/d' .gitignore > .gitignore.tmp && mv .gitignore.tmp .gitignore
          
          # Add generated code
          git add gen/
          git add .gitignore
          
          # Commit if there are changes
          git diff --staged --quiet || git commit -m "chore: update generated code and mocks"
          
          # Push release branch
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git latest --force
      
      - name: Create GitHub release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
      
      - name: Publish to npm
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          # Copy generated TypeScript to package root
          cp -r gen/ts/* .
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}