name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}
      
      - name: Lint
        run: buf lint
      
      - name: Format check
        run: buf format --diff --exit-code
      
      - name: Breaking change detection
        if: github.event_name == 'pull_request'
        continue-on-error: true
        run: |
          echo "Checking for breaking changes..."
          buf breaking --against "https://github.com/${{ github.repository }}.git#branch=main"

  verify-generated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}
      
      - name: Install mockgen
        run: go install github.com/golang/mock/mockgen@latest
      
      - name: Generate code
        run: |
          buf generate
          mkdir -p gen/go/github.com/KirkDiggler/rpg-api-protos/dnd5e/api/v1alpha1/mocks
          mockgen -source=gen/go/github.com/KirkDiggler/rpg-api-protos/dnd5e/api/v1alpha1/character_grpc.pb.go -destination=gen/go/github.com/KirkDiggler/rpg-api-protos/dnd5e/api/v1alpha1/mocks/character_service.go -package=mocks
      
      - name: Check if generated code is up to date
        run: |
          if [ -n "$(git status --porcelain gen/)" ]; then
            echo "Generated code is not up to date. Please run 'buf generate' and commit the changes."
            git diff gen/
            exit 1
          fi
      
      - name: Test Go compilation
        run: |
          cd gen/go
          go mod tidy
          go build ./...
      
      - name: Install TypeScript dependencies
        run: npm ci
      
      - name: Test TypeScript compilation
        run: |
          npx tsc --noEmit --project tsconfig.json